language: python
python:
  - "2.7"
  - "3.5"
cache: pip
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install -r requirements.txt
script:
  - coverage run run_tests.py 
